version: '3'
services:
  grpc-db:
    image: sameersbn/postgresql:10
    container_name: grpc-db
    restart: always
    network_mode: bridge
    volumes:
      - postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=dev
      - DB_PASS=dev
      - DB_NAME=impacter-posts-dev
      - PG_PASSWORD=dev

  grpc-server:
    container_name: grpc-server
    network_mode: bridge
    links:
      - grpc-db
    volumes:
      - "./protos:/protos:rw"
    build:
      context: ./server
    depends_on:
      - grpc-db

  grpc-client:
    container_name: grpc-client
    network_mode: bridge
    links:
      - grpc-server
    volumes:
      - "./protos:/protos:rw"
    build:
      context: ./client
    depends_on:
      - grpc-db
    ports:
      - "3000:3000"

volumes:
  postgresql:
